#!/bin/bash
#
#
# Every test must cause an *identical* result on an 80x25 vte
clear
cat resources/blank.tty
echo -n "[H" # OK, We're in the top-right of the default pool.
#
#
#

clear

for i in {1..25}; do
	echo "[$i;10HLine: $i"
done

./bin/cause-dump.sh
./bin/cause-exit.sh
